---
title: "SummarizingData.Rmd"
output: html_document
date: "2023-03-08"
---
```{r}
library(rio)
library(dplyr)
library(tidyr)
```

```{r}
Events <- import("Events.xlsx")
Results <- import("Results.xlsx")
Demographics <- import("Demographics.xlsx")
```

```{r}
Results %>% mutate(AchievingGroup = ifelse(ntile(Final_grade,2)==1,"Low achiever","High achiever")) -> Results
```

```{r}
EventsSummary <- Events %>% group_by(user,Action) %>% 
  summarize(n=length(Action)) %>% 
  pivot_wider(names_from = "Action", names_prefix = "Frequency.", values_from = "n", values_fill = 0)
```
```{r}
EventsSummary %>% rowwise %>% mutate(Frequency.Total = sum(across(1:(ncol(.)-1)))) %>% ungroup -> EventsSummary
```
```{r}
EventsSummary %>%  mutate(ActivityGroup = c("Low activity","Moderate activity","High activity")[ntile(Frequency.Total,3)]) -> EventsSummary
```


```{r}
EventsSummaryDemographics <- merge(Demographics, EventsSummary, by="user")
AllCombined <- merge(EventsSummaryDemographics, Results, by="user")
names(AllCombined)[1] <- "User"
```

```{r}
head(AllCombined)
```

```{r}
AllCombined 
```



```{r}
#export(AllCombined,"AllCombined.xlsx")
```

